#! /bin/bash

# This script is intended to be sourced, not run
if [[ $0 == $BASH_SOURCE ]]
then
    echo "This file should be run as"
    echo "  source $0"
    echo "and should not be run as"
    echo "  sh $0"
fi

vack ()
{ 
	local python_directory=$(dirname $BASH_SOURCE)
	local python_script=$python_directory/viack.py
	local bash_script=$python_directory/viack.sh
	rm -f $bash_script
	trap "{ rm -f $bash_script ; exit 0; }" EXIT
	if PYTHONPATH=$python_directory python $python_script "$@" > $bash_script 2>&1
	then bash $bash_script
	else cat $bash_script
	fi
}
